# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to HockeyApp"
    lane :beta do

    # clean
    gradle(
      task: 'clean',
      flags: '--no-daemon'
    )

    # build the release variant
    gradle(
      task: 'assembleDebug',
      flags: '--no-daemon'
    )

    changelog_notes = changelog_from_git_commits(
          include_merges: true,
          commits_count: 1,
          pretty: '%b %n%n %s (%h)'
    )

    hockey(
      api_token: "e0c22a9865a44d409a94e370977cf259",
      notes: changelog_notes +" CircleCI build " + ENV["CIRCLE_BUILD_NUM"],
      commit_sha: ENV["CIRCLE_SHA1"],
      build_server_url: ENV["CIRCLE_BUILD_URL"],
      repository_url: ENV["CIRCLE_REPOSITORY_URL"],
      notify: "1",
    )

  end
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
